# Generated by Django 4.2.11 on 2024-05-16 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Questions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chapter", models.IntegerField()),
                ("image", models.ImageField(upload_to="quiz_images/")),
                ("answer", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SolvedQuestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wasRight", models.BooleanField()),
                ("submitted_answer", models.CharField(max_length=225)),
                (
                    "solvedQuestions",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solvedQuestions",
                        to="question.questions",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userWhoHasSolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chapter", models.IntegerField()),
                ("examDateTime", models.DateTimeField()),
                ("examResult", models.JSONField()),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userWhoHadSolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
