# Generated by Django 5.0.6 on 2024-05-18 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField()),
                ('image', models.ImageField(upload_to='quiz_images/')),
                ('answer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExamLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField()),
                ('examDateTime', models.DateTimeField()),
                ('examResult', models.JSONField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userWhoSolved', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolvedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wasRight', models.BooleanField()),
                ('submitted_answer', models.CharField(max_length=255)),
                ('solvedQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solvedQuestion', to='question.question')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userWhoHadSolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('username', 'solvedQuestion')},
            },
        ),
    ]
