# Generated by Django 5.0.6 on 2024-05-18 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='examlog',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userWhoSolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questions',
            name='image',
            field=models.ImageField(upload_to='quiz_images'),
        ),
        migrations.AlterField(
            model_name='solvedquestions',
            name='submitted_answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='solvedquestions',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userWhoHadSolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='solvedquestions',
            unique_together={('username', 'solvedQuestions')},
        ),
    ]
