# Generated by Django 4.2.11 on 2024-05-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0002_alter_examlog_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questions",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
