<<<<<<< HEAD
# Generated by Django 4.2.11 on 2024-05-18 08:43
=======
# Generated by Django 5.0.6 on 2024-05-18 07:43
>>>>>>> 6b603dc6a94e134c468da104ec788ef4d4a08920

from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD
    dependencies = [
        ("question", "0002_alter_examlog_username_and_more"),
=======

    dependencies = [
        ('question', '0002_alter_examlog_username_and_more'),
>>>>>>> 6b603dc6a94e134c468da104ec788ef4d4a08920
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name="questions",
            name="image",
            field=models.ImageField(upload_to=""),
=======
            model_name='questions',
            name='image',
            field=models.ImageField(upload_to=''),
>>>>>>> 6b603dc6a94e134c468da104ec788ef4d4a08920
        ),
    ]
