# Generated by Django 4.2.11 on 2024-05-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0003_alter_questions_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questions",
            name="image",
            field=models.ImageField(upload_to="quiz_images/"),
        ),
    ]
